name: Build macOS

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build macOS app
      run: npm run dist:mac
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: dist/*.zip
